Improve helper scripts

diff --git a/misc/helper-scripts/taste-edit-concurrency-view b/misc/helper-scripts/taste-edit-concurrency-view
--- a/misc/helper-scripts/taste-edit-concurrency-view
+++ b/misc/helper-scripts/taste-edit-concurrency-view
@@ -1,19 +1,30 @@
 #!/bin/bash
 # TASTE Concurrency View Creator
 
-( cat ) | taste-progress-dialog.py &
-log_pid=$!
+# Initialise the progress bar
+myfifo=/tmp/$$$RANDOM
+mkfifo $myfifo
+tail -f $myfifo | taste-progress-dialog.py &
+
+function quit {
+    rm $myfifo
+    tailps=$(pstree -p $$ | grep tail | python -c "import sys, re; print re.search(r'tail\((.*)\)', [x for x in sys.stdin][0]).group(1)")
+    kill $tailps || xterm -e "echo Internal Error, unable to kill subprocess. Open a terminal and type 'pkill tail' to (hopefully) recover"
+    exit $1
+}
 
 # Logging with colors (only in a terminal)
 if [ -t 1 ] ; then
     COLORON="\e[1m\e[32m"
+    REDCOLORON="\e[1m\e[31m"
     COLOROFF="\e[0m"
 else
     COLORON=""
+    REDCOLORON=""
     COLOROFF=""
 fi
 INFO="${COLORON}[INFO]${COLOROFF}"
-ERROR="${COLORON}[ERROR]${COLOROFF}"
+ERROR="${REDCOLORON}[ERROR]${COLOROFF}"
 
 error=0
 NB_ARGS=3
@@ -24,38 +35,37 @@ if [ $# -eq $AUTO ]
 then
     if [[ -f InterfaceView.aadl && -f DeploymentView.aadl && -f DataView.aadl ]]
     then
-        echo 'Using InterfaceView.aadl, DeploymentView.aadl, DataView.aadl (defaults)'
+        echo -e "${INFO} Using InterfaceView.aadl, DeploymentView.aadl, DataView.aadl (defaults)"
 	INTERFACEVIEW=InterfaceView.aadl
         DEPLOYMENTVIEW=DeploymentView.aadl
         DATAVIEW=DataView.aadl
     else
         error=1
-        echo 'Error: Missing files (need InterfaceView.aadl, DeploymentView.aadl, DataView.aadl)'
-
+        echo -e "${ERROR} Missing files (need InterfaceView.aadl, DeploymentView.aadl, DataView.aadl)"
     fi
 else
     # Check if there are 3 parameters and that the files are all present
     if [[ $# -eq $NB_ARGS && -f "$1" && -f "$2" && -f "$3" ]]
     then
-        echo 'Loading interface, deployment and data views: "$1" "$2" "$3"'
+        echo -e "${INFO} Loading interface, deployment and data views: $1 $2 $3"
         INTERFACEVIEW="$1"
         DEPLOYMENTVIEW="$2"
         DATAVIEW="$3"
     else
         error=1
-        echo 'Error: specified files missing or wrong number of parameters'
+        echo -e "${ERROR} Specified files missing or wrong number of parameters"
     fi
 fi
 
 # Check if models are from V2 and convert to V1_3 accordingly
 V2=0
 grep "version => \"2" InterfaceView.aadl >/dev/null && {
-    echo '20 Analyse Interface View' > /proc/$log_pid/fd/0
+    echo '20 Analyse Interface View' > $myfifo
     echo -e "${INFO} Converting interface view from V2 to V1.3"
     TASTE --load-interface-view InterfaceView.aadl --export-interface-view-to-1_3 __iv_1_3.aadl
     INTERFACEVIEW=__iv_1_3.aadl
     echo -e "${INFO} Converting deployment view from V2 to V1.3"
-    echo '40 Analyse Deployment View' > /proc/$log_pid/fd/0
+    echo '40 Analyse Deployment View' > $myfifo
     TASTE --load-deployment-view "$DEPLOYMENTVIEW" --export-deployment-view-to-1_3 __dv_1_3.aadl
     DEPLOYMENTVIEW=__dv_1_3.aadl
     V2=1
@@ -66,10 +76,8 @@ if [ $error -eq 1 ]
 then
     echo -e "${ERROR} If you are using custom names for interface, deployment and data views, please specify them in order:
 Usage: taste-edit-concurrency-view InterfaceView.aadl DeploymentView.aadl DataView.aadl"
-    echo '100 Error' > /proc/$log_pid/fd/0
-    # Must kill the cat command still running in the background to release TASTE GUI
-    kill $(pstree -p $(jobs -x echo %1) | grep cat | cut -d \( -f 3 | cut -d \) -f 1)
-    exit -1
+    echo '100 Error' > $myfifo
+    quit 1
 fi
 
 AADL_PROPERTIES="$(taste-config --prefix)/share/config_ellidiss/TASTE_IV_Properties.aadl "
@@ -77,13 +85,13 @@ AADL_PROPERTIES+="$(taste-config --prefix)/share/config_ellidiss/TASTE_DV_Proper
 OCARINA_COMPONENTS="$(taste-config --prefix)/share/ocarina/AADLv2/ocarina_components.aadl"
 
 # Tempdir will not be deleted - OS shall make the cleanup (likely at reboot)
-echo '60 Parse Data View' > /proc/$log_pid/fd/0
+echo '60 Parse Data View' > $myfifo
 tempdir=$(mktemp -d)
 mono $(which taste-extract-asn-from-design.exe) -i "$INTERFACEVIEW" -j "$tempdir"/dataview-uniq.asn
 asn2aadlPlus "$tempdir"/dataview-uniq.asn "$tempdir"/dataview-uniq.aadl -aadlv2
 mono $(which taste-extract-asn-from-design.exe) -i "$INTERFACEVIEW" -k "$tempdir"/dataview-uniq.asn
 DATAVIEW="$tempdir"/dataview-uniq.aadl
-echo '80 Generate Concurrency View' > /proc/$log_pid/fd/0
+echo '80 Generate Concurrency View' > $myfifo
 CMD="buildsupport -i ${INTERFACEVIEW}
                   -c ${DEPLOYMENTVIEW}
                   -d ${DATAVIEW}
@@ -111,10 +119,8 @@ else
 ${CMD}
 "
     echo -e "${ERROR} Buildsupport reported errors - Fix your models before you can edit the Concurrency View"
-    echo '100 Error' > /proc/$log_pid/fd/0
-    # Must kill the cat command still running in the background to release TASTE GUI
-    kill $(pstree -p $(jobs -x echo %1) | grep cat | cut -d \( -f 3 | cut -d \) -f 1)
-    exit -2
+    echo '100 Error' > $myfifo
+    quit 2
 fi
 
 echo 'Running the Concurrency View editor from TASTE
@@ -135,8 +141,6 @@ else
     mv "$tempdir"/ConcurrencyView .
 fi
 
-echo '100 Done' > /proc/$log_pid/fd/0
+echo '100 Done' >  $myfifo
 
-# Must kill the cat command still running in the background to release TASTE GUI
-kill $(pstree -p $(jobs -x echo %1) | grep cat | cut -d \( -f 3 | cut -d \) -f 1)
-exit 0
+quit 0
